name: test
desc: test
runbooks:
- name: test
  desc: test
  selectors:
  - type: labelSelector
    selector: app=test
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.metadata.name}=attachdetach-controller'
  doc: test/test.md
- name: test1
  desc: test1
  selectors:
  - type: labelSelector
    selector: app=test
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.metadata.name}=attachdetach-controller'
  doc: test/test1.md
- name: test2
  desc: test2
  selectors:
  - type: labelSelector
    selector: test=test
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=Secret'
  - type: jsonPathSelector
    selector: '{.metadata.name}=bootstrap-token-abcdef'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=kube-system'
  doc: test/test2.md
