name: test
desc: test
runbooks:
- name: test
  desc: test
  selectors:
  - type: labelSelector
    selector: app=test
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.metadata.name}=attachdetach-controller'
  doc: test/test.md
